version: "3"
services:
    blazegraph:
        image: metaphacts/blazegraph-basic
        container_name: x3ml-debugger-blazegraph
        volumes:
            - ./output:/data

    platform:
        container_name: x3ml-debugger-platform
        image: swissartresearx/metaphacts-community:4.1.2
        ports:
            - ${PORT_PLATFORM}:8080
        volumes:
            - ./runtime:/runtime

    x3ml-debuggger:
        build: ./docker
        image: swissartresearx/x3ml-debugger
        container_name: x3ml-debugger-jobs
        volumes:
            - ./:/workdir
        ports:
            - ${PORT_JUPYTER}:8888